// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

#nullable disable

namespace StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720140952_AddCourseTable")]
    partial class AddCourseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(1125),
                            CreditHours = 0,
                            Description = "This is a C# programming course.",
                            Title = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(1127),
                            CreditHours = 0,
                            Description = "This is an ASP.NET Web API course.",
                            Title = "Asp Dot net Web API"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(1128),
                            CreditHours = 0,
                            Description = "This is a SQL Server course.",
                            Title = "SQL Server"
                        });
                });

            modelBuilder.Entity("StudentAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            BankAccount = "BD111",
                            City = "Dhaka",
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(951),
                            Name = "Rahim",
                            Password = "pass123"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            BankAccount = "BD222",
                            City = "Chittagong",
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(962),
                            Name = "Karim",
                            Password = "pass456"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            BankAccount = "BD333",
                            City = "Khulna",
                            CreatedAt = new DateTime(2026, 7, 20, 20, 9, 51, 665, DateTimeKind.Local).AddTicks(964),
                            Name = "Jamal",
                            Password = "pass789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
